name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
concurrency: 
  group: production # gh-pages was taken by gh pages
  cancel-in-progress: true
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: mikaeldui/actions/dotnet/setup@main
      with:
        dotnet-version: '6.0.x'

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish MasteriesQuest.Web/MasteriesQuest.Web.csproj -c Release -o release --nologo
    
    ## changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
    #- name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
    #  run: sed -i 's/<base href="\/" \/>/<base href="\/champion-mastery\/" \/>/g' release/wwwroot/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: release/wwwroot
        jekyll: false
        fqdn: masteries.quest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

